---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: terraform
    directory: modules/source
    schedule:
      interval: weekly
  - package-ecosystem: terraform
    directory: modules/destination
    schedule:
      interval: weekly
