---
name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    uses: appvia/appvia-cicd-workflows/.github/workflows/terraform-module-release.yml@313f07f46b44c4f3c82e878d71dc3182a0ce3c3d # main
    name: GitHub Release
