---
name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    uses: appvia/appvia-cicd-workflows/.github/workflows/terraform-module-release.yml@da2bf7ed16cc9778fedff463249466ca88069df5 # main
    name: GitHub Release
