---
name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    uses: appvia/appvia-cicd-workflows/.github/workflows/terraform-module-release.yml@7a4417e281f2b6fc8a8271b634bebeb11a7065e0 # main
    name: GitHub Release
