---
name: Terraform
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  module-validation:
    uses: appvia/appvia-cicd-workflows/.github/workflows/terraform-module-validation.yml@7a4417e281f2b6fc8a8271b634bebeb11a7065e0 # main
    name: Module Validation
    with:
      working-directory: examples/basic
