---
name: Terraform
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  module-validation:
    uses: appvia/appvia-cicd-workflows/.github/workflows/terraform-module-validation.yml@3164d438773efd653eab05d1422d20daf9374aee # main
    name: Module Validation
    with:
      working-directory: examples/basic
